controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robstride_position_controller:
      type: position_controllers/JointGroupPositionController
    robstride_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    robstride_effort_controller:
      type: effort_controllers/JointGroupEffortController

robstride_position_controller:
  ros__parameters:
    joints:
      - robstride_joint

robstride_velocity_controller:
  ros__parameters:
    joints:
      - robstride_joint

robstride_effort_controller:
  ros__parameters:
    joints:
      - robstride_joint
